sudo: false

language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

matrix:
  fast_finish: true

install:
  - composer selfupdate

before_script:
  - composer install --no-interaction --no-scripts

script:
  - ./vendor/bin/phpunit
